#include "utils/Data.hpp"

Data::Data() {
	std::cout << "TEST" << std::endl;
	_mime_types["html"] = "text/html";
	_mime_types["htm"] = "text/html";
	_mime_types["shtml"] = "text/html";
	_mime_types["css"] = "text/css";
	_mime_types["xml"] = "text/xml";
	_mime_types["gif"] = "image/gif";
	_mime_types["jpeg"] = "image/jpeg";
	_mime_types["jpg"] = "image/jpeg";
	_mime_types["js"] = "application/javascript";
	_mime_types["atom"] = "application/atom+xml";
	_mime_types["rss"] = "application/rss+xml";
	_mime_types["mml"] = "text/mathml";
	_mime_types["txt"] = "text/plain";
	_mime_types["jad"] = "text/vnd.sun.j2me.app-descriptor";
	_mime_types["wml"] = "text/vnd.wap.wml";
	_mime_types["htc"] = "text/x-component";
	_mime_types["png"] = "image/png";
	_mime_types["tif"] = "image/tiff";
	_mime_types["tiff"] = "image/tiff";
	_mime_types["wbmp"] = "image/vnd.wap.wbmp";
	_mime_types["ico"] = "image/x-icon";
	_mime_types["jng"] = "image/x-jng";
	_mime_types["bmp"] = "image/x-ms-bmp";
	_mime_types["svg"] = "image/svg+xml";
	_mime_types["svgz"] = "image/svg+xml";
	_mime_types["webp"] = "image/webp";
	_mime_types["woff"] = "application/font-woff";
	_mime_types["jar"] = "application/java-archive";
	_mime_types["war"] = "application/java-archive";
	_mime_types["ear"] = "application/java-archive";
	_mime_types["json"] = "application/json";
	_mime_types["hqx"] = "application/mac-binhex40";
	_mime_types["doc"] = "application/msword";
	_mime_types["pdf"] = "application/pdf";
	_mime_types["ps"] = "application/postscript";
	_mime_types["eps"] = "application/postscript";
	_mime_types["ai"] = "application/postscript";
	_mime_types["rtf"] = "application/rtf";
	_mime_types["m3u8"] = "application/vnd.apple.mpegurl";
	_mime_types["xls"] = "application/vnd.ms-excel";
	_mime_types["eot"] = "application/vnd.ms-fontobject";
	_mime_types["ppt"] = "application/vnd.ms-powerpoint";
	_mime_types["wmlc"] = "application/vnd.wap.wmlc";
	_mime_types["kml"] = "application/vnd.google-earth.kml+xml";
	_mime_types["kmz"] = "application/vnd.google-earth.kmz";
	_mime_types["7z"] = "application/x-7z-compressed";
	_mime_types["cco"] = "application/x-cocoa";
	_mime_types["jardiff"] = "application/x-java-archive-diff";
	_mime_types["jnlp"] = "application/x-java-jnlp-file";
	_mime_types["run"] = "application/x-makeself";
	_mime_types["pl"] = "application/x-perl";
	_mime_types["pm"] = "application/x-perl";
	_mime_types["prc"] = "application/x-pilot";
	_mime_types["pdb"] = "application/x-pilot";
	_mime_types["rar"] = "application/x-rar-compressed";
	_mime_types["rpm"] = "application/x-redhat-package-manager";
	_mime_types["sea"] = "application/x-sea";
	_mime_types["swf"] = "application/x-shockwave-flash";
	_mime_types["sit"] = "application/x-stuffit";
	_mime_types["tcl"] = "application/x-tcl";
	_mime_types["tk"] = "application/x-tcl";
	_mime_types["der"] = "application/x-x509-ca-cert";
	_mime_types["pem"] = "application/x-x509-ca-cert";
	_mime_types["crt"] = "application/x-x509-ca-cert";
	_mime_types["xpi"] = "application/x-xpinstall";
	_mime_types["xhtml"] = "application/xhtml+xml";
	_mime_types["xspf"] = "application/xspf+xml";
	_mime_types["zip"] = "application/zip";
	_mime_types["bin"] = "application/octet-stream";
	_mime_types["exe"] = "application/octet-stream";
	_mime_types["dll"] = "application/octet-stream";
	_mime_types["deb"] = "application/octet-stream";
	_mime_types["dmg"] = "application/octet-stream";
	_mime_types["iso"] = "application/octet-stream";
	_mime_types["img"] = "application/octet-stream";
	_mime_types["msi"] = "application/octet-stream";
	_mime_types["msp"] = "application/octet-stream";
	_mime_types["msm"] = "application/octet-stream";
	_mime_types["docx"] = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
	_mime_types["xlsx"] = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
	_mime_types["pptx"] = "application/vnd.openxmlformats-officedocument.presentationml.presentation";
	_mime_types["mid"] = "audio/midi";
	_mime_types["midi"] = "audio/midi";
	_mime_types["kar"] = "audio/midi";
	_mime_types["mp3"] = "audio/mpeg";
	_mime_types["ogg"] = "audio/ogg";
	_mime_types["m4a"] = "audio/x-m4a";
	_mime_types["ra"] = "audio/x-realaudio";
	_mime_types["3gpp"] = "video/3gpp";
	_mime_types["3gp"] = "video/3gpp";
	_mime_types["ts"] = "video/mp2t";
	_mime_types["mp4"] = "video/mp4";
	_mime_types["mpeg"] = "video/mpeg";
	_mime_types["mpg"] = "video/mpeg";
	_mime_types["mov"] = "video/quicktime";
	_mime_types["webm"] = "video/webm";
	_mime_types["flv"] = "video/x-flv";
	_mime_types["m4v"] = "video/x-m4v";
	_mime_types["mng"] = "video/x-mng";
	_mime_types["asx"] = "video/x-ms-asf";
	_mime_types["asf"] = "video/x-ms-asf";
	_mime_types["wmv"] = "video/x-ms-wmv";
	_mime_types["avi"] = "video/x-msvideo";
}

Data::~Data() {}

const std::map<std::string, std::string> &Data::getMimeTypes() const {
	return (_mime_types);
}
